[build]
  base    = "frontend"
  publish = "build/web"
  command = "git clone https://github.com/flutter/flutter.git --depth 1 -b 3.24.0 $HOME/flutter && export PATH=$PATH:$HOME/flutter/bin && flutter config --enable-web && flutter create . --platforms web && flutter pub get && flutter build web --release --dart-define=API_BASE_URL=https://promptreel-ai.onrender.com --dart-define=FLW_PUBLIC_KEY=FLWPUBK-361fd657794dc9b4413eee510c6d68d4-X"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
