//
//  Generated file. Do not edit.
//  This is a placeholder — the real file is auto-generated by `flutter pub get`
//  when you run the project in Xcode. Run `flutter pub get` and open ios/Runner.xcworkspace
//  to regenerate this file automatically.
//

#ifndef GeneratedPluginRegistrant_h
#define GeneratedPluginRegistrant_h

#import <Flutter/Flutter.h>

NS_ASSUME_NONNULL_BEGIN

@interface GeneratedPluginRegistrant : NSObject
+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry;
@end

NS_ASSUME_NONNULL_END
#endif /* GeneratedPluginRegistrant_h */
